### ISSUE TITLE
[WP] Back button while scanning

### ISSUE THREAD

**Issue by BladeMF** [aritchie/barcodes#4]
1. When awaiting Acr.BarCodes.BarCodes.Instance.Read and the user cancels, the task never returns. 
2. If the user cancels fast enough, an uncatchable exception is thrown:
The operation was canceled by the user. (Exception from HRESULT: 0x800704C7)
No stack trace is available.
3. When resuming the app with the scan active this exception is thrown: 
Initialization canceled by .Dispose().
Object name: 'Camera'.
No stack trace is available.
My code is surrounded by try/catch block and the catch is not entered.

The scanning itself works fine.

WP Silverlight 8.0 (Xamarin.Forms).

**Comment by aritchie** [comment]
1) Use the cancellation token.  When the background is pressed, cancel on the cancellation token source.  
2) Nothing I can do about this one.
3) Use the cancellation token.  When the app wants to go to the background, cancel on the cancellation token source.

**Comment by BladeMF** [comment]
HI Allan,
1) Why not just finish the task when closing the Page? The back button is pressed on a library-created page. Why otherwise is there Success member on the result?
2) What do you mean? My problem is not that an exception is thrown - it seems normal, but that the exception is uncatchable and my app will certainly crash.
3) That's okay apart from not being catchable again.

Sorry to keep pestering you.

**Comment by BladeMF** [comment]
Actually, now that I look through the code, I see that these issues are not from your code, but the ZXing. Kinda strange implementation.

**Comment by aritchie** [comment]
1) because it means I have to start monitoring those events.  I put in the cancellation token specifically to deal with these edge cases.
2) This is an issue with zxing.net.  It hasn't caused any grief in my enterprise apps, so I likely wouldn't dig to much into this.  I'd happily take any PR's around it though.
3) Same answer as 1.  The cancellation token will fix this issue as well.

**Comment by BladeMF** [comment]
Well, I wouldn't consider it an edge case - its a back button and it is platform specific. The page is created by ZXing so I can't imagine that I can get to wire its events easily without the fuss of dealing with the three operating systems.

What's your idea of trapping the back button and using the token?

**Comment by aritchie** [comment]
You can create a static cancellation token that sits at the application top end (app delegate or android service monitoring for app backgrounding).  When the app goes to the background , cancel the token source and recreate when the app resumes.  

For the second part, I wire in all of my viewmodels to state changes (start, appearing, disappearing) and kill any token sources on disappearing as well.  Doing it at this level is likely the best since it gives you the greatest flexibility.

Again, I consider this edge case because it is manageable with the API I've provided.  I can fix it from a zxing level, but why bother?  I use cancellation tokens in any case for other reasons (timeouts, etc), so I usually kill two birds with one stone.

**Comment by BladeMF** [comment]
Thanks, I will definitely try your approach - it is different from what I've used to and thus interesting.
And last question - how do I do custom screen/overlay for scanning?

**Comment by aritchie** [comment]
It isn't currently supported.  Difficult to make these custom in xplat scenarios.  I can plug Xamarin forms in here, but I want these plugins to be simple.

You can always create your implementation of ibarcodes though
